package com.kaige123.daomu.DAO.Mapper;

import com.kaige123.daomu.DAO.Bean.Financewater;
import com.kaige123.daomu.DAO.Bean.FinancewaterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FinancewaterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    long countByExample(FinancewaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByExample(FinancewaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByPrimaryKey(Long fwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insert(Financewater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insertSelective(Financewater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    List<Financewater> selectByExample(FinancewaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    Financewater selectByPrimaryKey(Long fwid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Financewater record, @Param("example") FinancewaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExample(@Param("record") Financewater record, @Param("example") FinancewaterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKeySelective(Financewater record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKey(Financewater record);
}