package com.kaige123.daomu.DAO.Mapper;

import com.kaige123.daomu.DAO.Bean.OSaid;
import com.kaige123.daomu.DAO.Bean.OSaidExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OSaidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    long countByExample(OSaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByExample(OSaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insert(OSaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insertSelective(OSaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    List<OSaid> selectByExample(OSaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    OSaid selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") OSaid record, @Param("example") OSaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExample(@Param("record") OSaid record, @Param("example") OSaidExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKeySelective(OSaid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table osaid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKey(OSaid record);
}