package com.kaige123.daomu.DAO.Mapper;

import com.kaige123.daomu.DAO.Bean.ResourceDownload;
import com.kaige123.daomu.DAO.Bean.ResourceDownloadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResourceDownloadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    long countByExample(ResourceDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByExample(ResourceDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByPrimaryKey(Long rdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insert(ResourceDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insertSelective(ResourceDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    List<ResourceDownload> selectByExample(ResourceDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    ResourceDownload selectByPrimaryKey(Long rdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") ResourceDownload record, @Param("example") ResourceDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExample(@Param("record") ResourceDownload record, @Param("example") ResourceDownloadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKeySelective(ResourceDownload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKey(ResourceDownload record);
}