package com.kaige123.daomu.DAO.Mapper;

import com.kaige123.daomu.DAO.Bean.Userlog;
import com.kaige123.daomu.DAO.Bean.UserlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    long countByExample(UserlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByExample(UserlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByPrimaryKey(String ulid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insert(Userlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insertSelective(Userlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    List<Userlog> selectByExample(UserlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    Userlog selectByPrimaryKey(String ulid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Userlog record, @Param("example") UserlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExample(@Param("record") Userlog record, @Param("example") UserlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKeySelective(Userlog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlog
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKey(Userlog record);
}