package com.kaige123.daomu.DAO.Mapper;

import com.kaige123.daomu.DAO.Bean.Vcomment;
import com.kaige123.daomu.DAO.Bean.VcommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VcommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    long countByExample(VcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByExample(VcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByPrimaryKey(Long vmid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insert(Vcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insertSelective(Vcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    List<Vcomment> selectByExample(VcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    Vcomment selectByPrimaryKey(Long vmid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Vcomment record, @Param("example") VcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExample(@Param("record") Vcomment record, @Param("example") VcommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKeySelective(Vcomment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcomment
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKey(Vcomment record);
}