package com.kaige123.daomu.DAO.Mapper;

import com.kaige123.daomu.DAO.Bean.Videobuyorder;
import com.kaige123.daomu.DAO.Bean.VideobuyorderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideobuyorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    long countByExample(VideobuyorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByExample(VideobuyorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insert(Videobuyorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insertSelective(Videobuyorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    List<Videobuyorder> selectByExample(VideobuyorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    Videobuyorder selectByPrimaryKey(String oid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Videobuyorder record, @Param("example") VideobuyorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExample(@Param("record") Videobuyorder record, @Param("example") VideobuyorderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKeySelective(Videobuyorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videobuyorder
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKey(Videobuyorder record);
}