package com.kaige123.daomu.DAO.Mapper;

import com.kaige123.daomu.DAO.Bean.Videotype;
import com.kaige123.daomu.DAO.Bean.VideotypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideotypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    long countByExample(VideotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByExample(VideotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByPrimaryKey(Long vtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insert(Videotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insertSelective(Videotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    List<Videotype> selectByExample(VideotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    Videotype selectByPrimaryKey(Long vtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Videotype record, @Param("example") VideotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExample(@Param("record") Videotype record, @Param("example") VideotypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKeySelective(Videotype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videotype
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKey(Videotype record);
}