package com.kaige123.daomu.DAO.Mapper;

import com.kaige123.daomu.DAO.Bean.Videocoures;
import com.kaige123.daomu.DAO.Bean.VideocouresExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideocouresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    long countByExample(VideocouresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByExample(VideocouresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int deleteByPrimaryKey(Long vcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insert(Videocoures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int insertSelective(Videocoures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    List<Videocoures> selectByExample(VideocouresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    Videocoures selectByPrimaryKey(Long vcid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") Videocoures record, @Param("example") VideocouresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByExample(@Param("record") Videocoures record, @Param("example") VideocouresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKeySelective(Videocoures record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table videocoures
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    int updateByPrimaryKey(Videocoures record);
}