package com.kaige123.daomu.DAO.Bean;

import java.util.Date;

public class Banner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.bid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.title
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.img
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.src
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String src;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column banner.time
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.bid
     *
     * @return the value of banner.bid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.bid
     *
     * @param bid the value for banner.bid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setBid(Long bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.title
     *
     * @return the value of banner.title
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.title
     *
     * @param title the value for banner.title
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.img
     *
     * @return the value of banner.img
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.img
     *
     * @param img the value for banner.img
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.src
     *
     * @return the value of banner.src
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.src
     *
     * @param src the value for banner.src
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column banner.time
     *
     * @return the value of banner.time
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column banner.time
     *
     * @param time the value for banner.time
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}