package com.kaige123.daomu.DAO.Bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DrawmonyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public DrawmonyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDmidIsNull() {
            addCriterion("dmid is null");
            return (Criteria) this;
        }

        public Criteria andDmidIsNotNull() {
            addCriterion("dmid is not null");
            return (Criteria) this;
        }

        public Criteria andDmidEqualTo(Long value) {
            addCriterion("dmid =", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidNotEqualTo(Long value) {
            addCriterion("dmid <>", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidGreaterThan(Long value) {
            addCriterion("dmid >", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidGreaterThanOrEqualTo(Long value) {
            addCriterion("dmid >=", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidLessThan(Long value) {
            addCriterion("dmid <", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidLessThanOrEqualTo(Long value) {
            addCriterion("dmid <=", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidIn(List<Long> values) {
            addCriterion("dmid in", values, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidNotIn(List<Long> values) {
            addCriterion("dmid not in", values, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidBetween(Long value1, Long value2) {
            addCriterion("dmid between", value1, value2, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidNotBetween(Long value1, Long value2) {
            addCriterion("dmid not between", value1, value2, "dmid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Long value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Long value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Long value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Long value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Long value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Long value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Long> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Long> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Long value1, Long value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Long value1, Long value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andMonyIsNull() {
            addCriterion("mony is null");
            return (Criteria) this;
        }

        public Criteria andMonyIsNotNull() {
            addCriterion("mony is not null");
            return (Criteria) this;
        }

        public Criteria andMonyEqualTo(BigDecimal value) {
            addCriterion("mony =", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyNotEqualTo(BigDecimal value) {
            addCriterion("mony <>", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyGreaterThan(BigDecimal value) {
            addCriterion("mony >", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mony >=", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyLessThan(BigDecimal value) {
            addCriterion("mony <", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mony <=", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyIn(List<BigDecimal> values) {
            addCriterion("mony in", values, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyNotIn(List<BigDecimal> values) {
            addCriterion("mony not in", values, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mony between", value1, value2, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mony not between", value1, value2, "mony");
            return (Criteria) this;
        }

        public Criteria andHandeldateIsNull() {
            addCriterion("HandelDate is null");
            return (Criteria) this;
        }

        public Criteria andHandeldateIsNotNull() {
            addCriterion("HandelDate is not null");
            return (Criteria) this;
        }

        public Criteria andHandeldateEqualTo(Date value) {
            addCriterion("HandelDate =", value, "handeldate");
            return (Criteria) this;
        }

        public Criteria andHandeldateNotEqualTo(Date value) {
            addCriterion("HandelDate <>", value, "handeldate");
            return (Criteria) this;
        }

        public Criteria andHandeldateGreaterThan(Date value) {
            addCriterion("HandelDate >", value, "handeldate");
            return (Criteria) this;
        }

        public Criteria andHandeldateGreaterThanOrEqualTo(Date value) {
            addCriterion("HandelDate >=", value, "handeldate");
            return (Criteria) this;
        }

        public Criteria andHandeldateLessThan(Date value) {
            addCriterion("HandelDate <", value, "handeldate");
            return (Criteria) this;
        }

        public Criteria andHandeldateLessThanOrEqualTo(Date value) {
            addCriterion("HandelDate <=", value, "handeldate");
            return (Criteria) this;
        }

        public Criteria andHandeldateIn(List<Date> values) {
            addCriterion("HandelDate in", values, "handeldate");
            return (Criteria) this;
        }

        public Criteria andHandeldateNotIn(List<Date> values) {
            addCriterion("HandelDate not in", values, "handeldate");
            return (Criteria) this;
        }

        public Criteria andHandeldateBetween(Date value1, Date value2) {
            addCriterion("HandelDate between", value1, value2, "handeldate");
            return (Criteria) this;
        }

        public Criteria andHandeldateNotBetween(Date value1, Date value2) {
            addCriterion("HandelDate not between", value1, value2, "handeldate");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNull() {
            addCriterion("adminid is null");
            return (Criteria) this;
        }

        public Criteria andAdminidIsNotNull() {
            addCriterion("adminid is not null");
            return (Criteria) this;
        }

        public Criteria andAdminidEqualTo(Integer value) {
            addCriterion("adminid =", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotEqualTo(Integer value) {
            addCriterion("adminid <>", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThan(Integer value) {
            addCriterion("adminid >", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidGreaterThanOrEqualTo(Integer value) {
            addCriterion("adminid >=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThan(Integer value) {
            addCriterion("adminid <", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidLessThanOrEqualTo(Integer value) {
            addCriterion("adminid <=", value, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidIn(List<Integer> values) {
            addCriterion("adminid in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotIn(List<Integer> values) {
            addCriterion("adminid not in", values, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidBetween(Integer value1, Integer value2) {
            addCriterion("adminid between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andAdminidNotBetween(Integer value1, Integer value2) {
            addCriterion("adminid not between", value1, value2, "adminid");
            return (Criteria) this;
        }

        public Criteria andText1IsNull() {
            addCriterion("text1 is null");
            return (Criteria) this;
        }

        public Criteria andText1IsNotNull() {
            addCriterion("text1 is not null");
            return (Criteria) this;
        }

        public Criteria andText1EqualTo(String value) {
            addCriterion("text1 =", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotEqualTo(String value) {
            addCriterion("text1 <>", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1GreaterThan(String value) {
            addCriterion("text1 >", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1GreaterThanOrEqualTo(String value) {
            addCriterion("text1 >=", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1LessThan(String value) {
            addCriterion("text1 <", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1LessThanOrEqualTo(String value) {
            addCriterion("text1 <=", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1Like(String value) {
            addCriterion("text1 like", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotLike(String value) {
            addCriterion("text1 not like", value, "text1");
            return (Criteria) this;
        }

        public Criteria andText1In(List<String> values) {
            addCriterion("text1 in", values, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotIn(List<String> values) {
            addCriterion("text1 not in", values, "text1");
            return (Criteria) this;
        }

        public Criteria andText1Between(String value1, String value2) {
            addCriterion("text1 between", value1, value2, "text1");
            return (Criteria) this;
        }

        public Criteria andText1NotBetween(String value1, String value2) {
            addCriterion("text1 not between", value1, value2, "text1");
            return (Criteria) this;
        }

        public Criteria andText2IsNull() {
            addCriterion("text2 is null");
            return (Criteria) this;
        }

        public Criteria andText2IsNotNull() {
            addCriterion("text2 is not null");
            return (Criteria) this;
        }

        public Criteria andText2EqualTo(String value) {
            addCriterion("text2 =", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotEqualTo(String value) {
            addCriterion("text2 <>", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2GreaterThan(String value) {
            addCriterion("text2 >", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2GreaterThanOrEqualTo(String value) {
            addCriterion("text2 >=", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2LessThan(String value) {
            addCriterion("text2 <", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2LessThanOrEqualTo(String value) {
            addCriterion("text2 <=", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2Like(String value) {
            addCriterion("text2 like", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotLike(String value) {
            addCriterion("text2 not like", value, "text2");
            return (Criteria) this;
        }

        public Criteria andText2In(List<String> values) {
            addCriterion("text2 in", values, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotIn(List<String> values) {
            addCriterion("text2 not in", values, "text2");
            return (Criteria) this;
        }

        public Criteria andText2Between(String value1, String value2) {
            addCriterion("text2 between", value1, value2, "text2");
            return (Criteria) this;
        }

        public Criteria andText2NotBetween(String value1, String value2) {
            addCriterion("text2 not between", value1, value2, "text2");
            return (Criteria) this;
        }

        public Criteria andText3IsNull() {
            addCriterion("text3 is null");
            return (Criteria) this;
        }

        public Criteria andText3IsNotNull() {
            addCriterion("text3 is not null");
            return (Criteria) this;
        }

        public Criteria andText3EqualTo(String value) {
            addCriterion("text3 =", value, "text3");
            return (Criteria) this;
        }

        public Criteria andText3NotEqualTo(String value) {
            addCriterion("text3 <>", value, "text3");
            return (Criteria) this;
        }

        public Criteria andText3GreaterThan(String value) {
            addCriterion("text3 >", value, "text3");
            return (Criteria) this;
        }

        public Criteria andText3GreaterThanOrEqualTo(String value) {
            addCriterion("text3 >=", value, "text3");
            return (Criteria) this;
        }

        public Criteria andText3LessThan(String value) {
            addCriterion("text3 <", value, "text3");
            return (Criteria) this;
        }

        public Criteria andText3LessThanOrEqualTo(String value) {
            addCriterion("text3 <=", value, "text3");
            return (Criteria) this;
        }

        public Criteria andText3Like(String value) {
            addCriterion("text3 like", value, "text3");
            return (Criteria) this;
        }

        public Criteria andText3NotLike(String value) {
            addCriterion("text3 not like", value, "text3");
            return (Criteria) this;
        }

        public Criteria andText3In(List<String> values) {
            addCriterion("text3 in", values, "text3");
            return (Criteria) this;
        }

        public Criteria andText3NotIn(List<String> values) {
            addCriterion("text3 not in", values, "text3");
            return (Criteria) this;
        }

        public Criteria andText3Between(String value1, String value2) {
            addCriterion("text3 between", value1, value2, "text3");
            return (Criteria) this;
        }

        public Criteria andText3NotBetween(String value1, String value2) {
            addCriterion("text3 not between", value1, value2, "text3");
            return (Criteria) this;
        }

        public Criteria andText4IsNull() {
            addCriterion("text4 is null");
            return (Criteria) this;
        }

        public Criteria andText4IsNotNull() {
            addCriterion("text4 is not null");
            return (Criteria) this;
        }

        public Criteria andText4EqualTo(String value) {
            addCriterion("text4 =", value, "text4");
            return (Criteria) this;
        }

        public Criteria andText4NotEqualTo(String value) {
            addCriterion("text4 <>", value, "text4");
            return (Criteria) this;
        }

        public Criteria andText4GreaterThan(String value) {
            addCriterion("text4 >", value, "text4");
            return (Criteria) this;
        }

        public Criteria andText4GreaterThanOrEqualTo(String value) {
            addCriterion("text4 >=", value, "text4");
            return (Criteria) this;
        }

        public Criteria andText4LessThan(String value) {
            addCriterion("text4 <", value, "text4");
            return (Criteria) this;
        }

        public Criteria andText4LessThanOrEqualTo(String value) {
            addCriterion("text4 <=", value, "text4");
            return (Criteria) this;
        }

        public Criteria andText4Like(String value) {
            addCriterion("text4 like", value, "text4");
            return (Criteria) this;
        }

        public Criteria andText4NotLike(String value) {
            addCriterion("text4 not like", value, "text4");
            return (Criteria) this;
        }

        public Criteria andText4In(List<String> values) {
            addCriterion("text4 in", values, "text4");
            return (Criteria) this;
        }

        public Criteria andText4NotIn(List<String> values) {
            addCriterion("text4 not in", values, "text4");
            return (Criteria) this;
        }

        public Criteria andText4Between(String value1, String value2) {
            addCriterion("text4 between", value1, value2, "text4");
            return (Criteria) this;
        }

        public Criteria andText4NotBetween(String value1, String value2) {
            addCriterion("text4 not between", value1, value2, "text4");
            return (Criteria) this;
        }

        public Criteria andText5IsNull() {
            addCriterion("text5 is null");
            return (Criteria) this;
        }

        public Criteria andText5IsNotNull() {
            addCriterion("text5 is not null");
            return (Criteria) this;
        }

        public Criteria andText5EqualTo(String value) {
            addCriterion("text5 =", value, "text5");
            return (Criteria) this;
        }

        public Criteria andText5NotEqualTo(String value) {
            addCriterion("text5 <>", value, "text5");
            return (Criteria) this;
        }

        public Criteria andText5GreaterThan(String value) {
            addCriterion("text5 >", value, "text5");
            return (Criteria) this;
        }

        public Criteria andText5GreaterThanOrEqualTo(String value) {
            addCriterion("text5 >=", value, "text5");
            return (Criteria) this;
        }

        public Criteria andText5LessThan(String value) {
            addCriterion("text5 <", value, "text5");
            return (Criteria) this;
        }

        public Criteria andText5LessThanOrEqualTo(String value) {
            addCriterion("text5 <=", value, "text5");
            return (Criteria) this;
        }

        public Criteria andText5Like(String value) {
            addCriterion("text5 like", value, "text5");
            return (Criteria) this;
        }

        public Criteria andText5NotLike(String value) {
            addCriterion("text5 not like", value, "text5");
            return (Criteria) this;
        }

        public Criteria andText5In(List<String> values) {
            addCriterion("text5 in", values, "text5");
            return (Criteria) this;
        }

        public Criteria andText5NotIn(List<String> values) {
            addCriterion("text5 not in", values, "text5");
            return (Criteria) this;
        }

        public Criteria andText5Between(String value1, String value2) {
            addCriterion("text5 between", value1, value2, "text5");
            return (Criteria) this;
        }

        public Criteria andText5NotBetween(String value1, String value2) {
            addCriterion("text5 not between", value1, value2, "text5");
            return (Criteria) this;
        }

        public Criteria andServerchargeIsNull() {
            addCriterion("ServerCharge is null");
            return (Criteria) this;
        }

        public Criteria andServerchargeIsNotNull() {
            addCriterion("ServerCharge is not null");
            return (Criteria) this;
        }

        public Criteria andServerchargeEqualTo(BigDecimal value) {
            addCriterion("ServerCharge =", value, "servercharge");
            return (Criteria) this;
        }

        public Criteria andServerchargeNotEqualTo(BigDecimal value) {
            addCriterion("ServerCharge <>", value, "servercharge");
            return (Criteria) this;
        }

        public Criteria andServerchargeGreaterThan(BigDecimal value) {
            addCriterion("ServerCharge >", value, "servercharge");
            return (Criteria) this;
        }

        public Criteria andServerchargeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ServerCharge >=", value, "servercharge");
            return (Criteria) this;
        }

        public Criteria andServerchargeLessThan(BigDecimal value) {
            addCriterion("ServerCharge <", value, "servercharge");
            return (Criteria) this;
        }

        public Criteria andServerchargeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ServerCharge <=", value, "servercharge");
            return (Criteria) this;
        }

        public Criteria andServerchargeIn(List<BigDecimal> values) {
            addCriterion("ServerCharge in", values, "servercharge");
            return (Criteria) this;
        }

        public Criteria andServerchargeNotIn(List<BigDecimal> values) {
            addCriterion("ServerCharge not in", values, "servercharge");
            return (Criteria) this;
        }

        public Criteria andServerchargeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ServerCharge between", value1, value2, "servercharge");
            return (Criteria) this;
        }

        public Criteria andServerchargeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ServerCharge not between", value1, value2, "servercharge");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andHandletypeIsNull() {
            addCriterion("HandleType is null");
            return (Criteria) this;
        }

        public Criteria andHandletypeIsNotNull() {
            addCriterion("HandleType is not null");
            return (Criteria) this;
        }

        public Criteria andHandletypeEqualTo(String value) {
            addCriterion("HandleType =", value, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeNotEqualTo(String value) {
            addCriterion("HandleType <>", value, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeGreaterThan(String value) {
            addCriterion("HandleType >", value, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeGreaterThanOrEqualTo(String value) {
            addCriterion("HandleType >=", value, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeLessThan(String value) {
            addCriterion("HandleType <", value, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeLessThanOrEqualTo(String value) {
            addCriterion("HandleType <=", value, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeLike(String value) {
            addCriterion("HandleType like", value, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeNotLike(String value) {
            addCriterion("HandleType not like", value, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeIn(List<String> values) {
            addCriterion("HandleType in", values, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeNotIn(List<String> values) {
            addCriterion("HandleType not in", values, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeBetween(String value1, String value2) {
            addCriterion("HandleType between", value1, value2, "handletype");
            return (Criteria) this;
        }

        public Criteria andHandletypeNotBetween(String value1, String value2) {
            addCriterion("HandleType not between", value1, value2, "handletype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drawmony
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 13 11:12:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drawmony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}