package com.kaige123.daomu.DAO.Bean;

import java.math.BigDecimal;

public class Financewater {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financewater.fwid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long fwid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financewater.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financewater.payType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financewater.fwType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String fwtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financewater.produceMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private BigDecimal producemony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financewater.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String vcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financewater.dmid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String dmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column financewater.tid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financewater.fwid
     *
     * @return the value of financewater.fwid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getFwid() {
        return fwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financewater.fwid
     *
     * @param fwid the value for financewater.fwid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setFwid(Long fwid) {
        this.fwid = fwid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financewater.uid
     *
     * @return the value of financewater.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financewater.uid
     *
     * @param uid the value for financewater.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financewater.payType
     *
     * @return the value of financewater.payType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financewater.payType
     *
     * @param paytype the value for financewater.payType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financewater.fwType
     *
     * @return the value of financewater.fwType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getFwtype() {
        return fwtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financewater.fwType
     *
     * @param fwtype the value for financewater.fwType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setFwtype(String fwtype) {
        this.fwtype = fwtype == null ? null : fwtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financewater.produceMony
     *
     * @return the value of financewater.produceMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public BigDecimal getProducemony() {
        return producemony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financewater.produceMony
     *
     * @param producemony the value for financewater.produceMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setProducemony(BigDecimal producemony) {
        this.producemony = producemony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financewater.vcid
     *
     * @return the value of financewater.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getVcid() {
        return vcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financewater.vcid
     *
     * @param vcid the value for financewater.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVcid(String vcid) {
        this.vcid = vcid == null ? null : vcid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financewater.dmid
     *
     * @return the value of financewater.dmid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getDmid() {
        return dmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financewater.dmid
     *
     * @param dmid the value for financewater.dmid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setDmid(String dmid) {
        this.dmid = dmid == null ? null : dmid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column financewater.tid
     *
     * @return the value of financewater.tid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column financewater.tid
     *
     * @param tid the value for financewater.tid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setTid(Long tid) {
        this.tid = tid;
    }
}