package com.kaige123.daomu.DAO.Bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FinancewaterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public FinancewaterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFwidIsNull() {
            addCriterion("fwid is null");
            return (Criteria) this;
        }

        public Criteria andFwidIsNotNull() {
            addCriterion("fwid is not null");
            return (Criteria) this;
        }

        public Criteria andFwidEqualTo(Long value) {
            addCriterion("fwid =", value, "fwid");
            return (Criteria) this;
        }

        public Criteria andFwidNotEqualTo(Long value) {
            addCriterion("fwid <>", value, "fwid");
            return (Criteria) this;
        }

        public Criteria andFwidGreaterThan(Long value) {
            addCriterion("fwid >", value, "fwid");
            return (Criteria) this;
        }

        public Criteria andFwidGreaterThanOrEqualTo(Long value) {
            addCriterion("fwid >=", value, "fwid");
            return (Criteria) this;
        }

        public Criteria andFwidLessThan(Long value) {
            addCriterion("fwid <", value, "fwid");
            return (Criteria) this;
        }

        public Criteria andFwidLessThanOrEqualTo(Long value) {
            addCriterion("fwid <=", value, "fwid");
            return (Criteria) this;
        }

        public Criteria andFwidIn(List<Long> values) {
            addCriterion("fwid in", values, "fwid");
            return (Criteria) this;
        }

        public Criteria andFwidNotIn(List<Long> values) {
            addCriterion("fwid not in", values, "fwid");
            return (Criteria) this;
        }

        public Criteria andFwidBetween(Long value1, Long value2) {
            addCriterion("fwid between", value1, value2, "fwid");
            return (Criteria) this;
        }

        public Criteria andFwidNotBetween(Long value1, Long value2) {
            addCriterion("fwid not between", value1, value2, "fwid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Long value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Long value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Long value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Long value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Long value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Long value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Long> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Long> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Long value1, Long value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Long value1, Long value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNull() {
            addCriterion("payType is null");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNotNull() {
            addCriterion("payType is not null");
            return (Criteria) this;
        }

        public Criteria andPaytypeEqualTo(String value) {
            addCriterion("payType =", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotEqualTo(String value) {
            addCriterion("payType <>", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThan(String value) {
            addCriterion("payType >", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThanOrEqualTo(String value) {
            addCriterion("payType >=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThan(String value) {
            addCriterion("payType <", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThanOrEqualTo(String value) {
            addCriterion("payType <=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLike(String value) {
            addCriterion("payType like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotLike(String value) {
            addCriterion("payType not like", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeIn(List<String> values) {
            addCriterion("payType in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotIn(List<String> values) {
            addCriterion("payType not in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeBetween(String value1, String value2) {
            addCriterion("payType between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotBetween(String value1, String value2) {
            addCriterion("payType not between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andFwtypeIsNull() {
            addCriterion("fwType is null");
            return (Criteria) this;
        }

        public Criteria andFwtypeIsNotNull() {
            addCriterion("fwType is not null");
            return (Criteria) this;
        }

        public Criteria andFwtypeEqualTo(String value) {
            addCriterion("fwType =", value, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeNotEqualTo(String value) {
            addCriterion("fwType <>", value, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeGreaterThan(String value) {
            addCriterion("fwType >", value, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeGreaterThanOrEqualTo(String value) {
            addCriterion("fwType >=", value, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeLessThan(String value) {
            addCriterion("fwType <", value, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeLessThanOrEqualTo(String value) {
            addCriterion("fwType <=", value, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeLike(String value) {
            addCriterion("fwType like", value, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeNotLike(String value) {
            addCriterion("fwType not like", value, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeIn(List<String> values) {
            addCriterion("fwType in", values, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeNotIn(List<String> values) {
            addCriterion("fwType not in", values, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeBetween(String value1, String value2) {
            addCriterion("fwType between", value1, value2, "fwtype");
            return (Criteria) this;
        }

        public Criteria andFwtypeNotBetween(String value1, String value2) {
            addCriterion("fwType not between", value1, value2, "fwtype");
            return (Criteria) this;
        }

        public Criteria andProducemonyIsNull() {
            addCriterion("produceMony is null");
            return (Criteria) this;
        }

        public Criteria andProducemonyIsNotNull() {
            addCriterion("produceMony is not null");
            return (Criteria) this;
        }

        public Criteria andProducemonyEqualTo(BigDecimal value) {
            addCriterion("produceMony =", value, "producemony");
            return (Criteria) this;
        }

        public Criteria andProducemonyNotEqualTo(BigDecimal value) {
            addCriterion("produceMony <>", value, "producemony");
            return (Criteria) this;
        }

        public Criteria andProducemonyGreaterThan(BigDecimal value) {
            addCriterion("produceMony >", value, "producemony");
            return (Criteria) this;
        }

        public Criteria andProducemonyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("produceMony >=", value, "producemony");
            return (Criteria) this;
        }

        public Criteria andProducemonyLessThan(BigDecimal value) {
            addCriterion("produceMony <", value, "producemony");
            return (Criteria) this;
        }

        public Criteria andProducemonyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("produceMony <=", value, "producemony");
            return (Criteria) this;
        }

        public Criteria andProducemonyIn(List<BigDecimal> values) {
            addCriterion("produceMony in", values, "producemony");
            return (Criteria) this;
        }

        public Criteria andProducemonyNotIn(List<BigDecimal> values) {
            addCriterion("produceMony not in", values, "producemony");
            return (Criteria) this;
        }

        public Criteria andProducemonyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("produceMony between", value1, value2, "producemony");
            return (Criteria) this;
        }

        public Criteria andProducemonyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("produceMony not between", value1, value2, "producemony");
            return (Criteria) this;
        }

        public Criteria andVcidIsNull() {
            addCriterion("vcid is null");
            return (Criteria) this;
        }

        public Criteria andVcidIsNotNull() {
            addCriterion("vcid is not null");
            return (Criteria) this;
        }

        public Criteria andVcidEqualTo(String value) {
            addCriterion("vcid =", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidNotEqualTo(String value) {
            addCriterion("vcid <>", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidGreaterThan(String value) {
            addCriterion("vcid >", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidGreaterThanOrEqualTo(String value) {
            addCriterion("vcid >=", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidLessThan(String value) {
            addCriterion("vcid <", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidLessThanOrEqualTo(String value) {
            addCriterion("vcid <=", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidLike(String value) {
            addCriterion("vcid like", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidNotLike(String value) {
            addCriterion("vcid not like", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidIn(List<String> values) {
            addCriterion("vcid in", values, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidNotIn(List<String> values) {
            addCriterion("vcid not in", values, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidBetween(String value1, String value2) {
            addCriterion("vcid between", value1, value2, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidNotBetween(String value1, String value2) {
            addCriterion("vcid not between", value1, value2, "vcid");
            return (Criteria) this;
        }

        public Criteria andDmidIsNull() {
            addCriterion("dmid is null");
            return (Criteria) this;
        }

        public Criteria andDmidIsNotNull() {
            addCriterion("dmid is not null");
            return (Criteria) this;
        }

        public Criteria andDmidEqualTo(String value) {
            addCriterion("dmid =", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidNotEqualTo(String value) {
            addCriterion("dmid <>", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidGreaterThan(String value) {
            addCriterion("dmid >", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidGreaterThanOrEqualTo(String value) {
            addCriterion("dmid >=", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidLessThan(String value) {
            addCriterion("dmid <", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidLessThanOrEqualTo(String value) {
            addCriterion("dmid <=", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidLike(String value) {
            addCriterion("dmid like", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidNotLike(String value) {
            addCriterion("dmid not like", value, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidIn(List<String> values) {
            addCriterion("dmid in", values, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidNotIn(List<String> values) {
            addCriterion("dmid not in", values, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidBetween(String value1, String value2) {
            addCriterion("dmid between", value1, value2, "dmid");
            return (Criteria) this;
        }

        public Criteria andDmidNotBetween(String value1, String value2) {
            addCriterion("dmid not between", value1, value2, "dmid");
            return (Criteria) this;
        }

        public Criteria andTidIsNull() {
            addCriterion("tid is null");
            return (Criteria) this;
        }

        public Criteria andTidIsNotNull() {
            addCriterion("tid is not null");
            return (Criteria) this;
        }

        public Criteria andTidEqualTo(Long value) {
            addCriterion("tid =", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotEqualTo(Long value) {
            addCriterion("tid <>", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThan(Long value) {
            addCriterion("tid >", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThanOrEqualTo(Long value) {
            addCriterion("tid >=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThan(Long value) {
            addCriterion("tid <", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThanOrEqualTo(Long value) {
            addCriterion("tid <=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidIn(List<Long> values) {
            addCriterion("tid in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotIn(List<Long> values) {
            addCriterion("tid not in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidBetween(Long value1, Long value2) {
            addCriterion("tid between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotBetween(Long value1, Long value2) {
            addCriterion("tid not between", value1, value2, "tid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table financewater
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 13 11:12:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table financewater
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}