package com.kaige123.daomu.DAO.Bean;

public class OSaid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaid.aid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaid.pohone
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String pohone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaid.password
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaid.state
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaid.post
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaid.logintime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String logintime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaid.aid
     *
     * @return the value of osaid.aid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaid.aid
     *
     * @param aid the value for osaid.aid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaid.pohone
     *
     * @return the value of osaid.pohone
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getPohone() {
        return pohone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaid.pohone
     *
     * @param pohone the value for osaid.pohone
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setPohone(String pohone) {
        this.pohone = pohone == null ? null : pohone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaid.password
     *
     * @return the value of osaid.password
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaid.password
     *
     * @param password the value for osaid.password
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaid.state
     *
     * @return the value of osaid.state
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaid.state
     *
     * @param state the value for osaid.state
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaid.post
     *
     * @return the value of osaid.post
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaid.post
     *
     * @param post the value for osaid.post
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaid.logintime
     *
     * @return the value of osaid.logintime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaid.logintime
     *
     * @param logintime the value for osaid.logintime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setLogintime(String logintime) {
        this.logintime = logintime == null ? null : logintime.trim();
    }
}