package com.kaige123.daomu.DAO.Bean;

import java.util.Date;

public class OSaidlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaidlog.alid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long alid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaidlog.aid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaidlog.method
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaidlog.paramter
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String paramter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaidlog.ip
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osaidlog.optionstime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Date optionstime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaidlog.alid
     *
     * @return the value of osaidlog.alid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getAlid() {
        return alid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaidlog.alid
     *
     * @param alid the value for osaidlog.alid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setAlid(Long alid) {
        this.alid = alid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaidlog.aid
     *
     * @return the value of osaidlog.aid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaidlog.aid
     *
     * @param aid the value for osaidlog.aid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setAid(Long aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaidlog.method
     *
     * @return the value of osaidlog.method
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaidlog.method
     *
     * @param method the value for osaidlog.method
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaidlog.paramter
     *
     * @return the value of osaidlog.paramter
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getParamter() {
        return paramter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaidlog.paramter
     *
     * @param paramter the value for osaidlog.paramter
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setParamter(String paramter) {
        this.paramter = paramter == null ? null : paramter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaidlog.ip
     *
     * @return the value of osaidlog.ip
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaidlog.ip
     *
     * @param ip the value for osaidlog.ip
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osaidlog.optionstime
     *
     * @return the value of osaidlog.optionstime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Date getOptionstime() {
        return optionstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osaidlog.optionstime
     *
     * @param optionstime the value for osaidlog.optionstime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setOptionstime(Date optionstime) {
        this.optionstime = optionstime;
    }
}