package com.kaige123.daomu.DAO.Bean;

public class OSconfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osconfig.k
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String k;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osconfig.y
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column osconfig.i
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String i;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osconfig.k
     *
     * @return the value of osconfig.k
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getK() {
        return k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osconfig.k
     *
     * @param k the value for osconfig.k
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setK(String k) {
        this.k = k == null ? null : k.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osconfig.y
     *
     * @return the value of osconfig.y
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osconfig.y
     *
     * @param y the value for osconfig.y
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setY(String y) {
        this.y = y == null ? null : y.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column osconfig.i
     *
     * @return the value of osconfig.i
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getI() {
        return i;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column osconfig.i
     *
     * @param i the value for osconfig.i
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setI(String i) {
        this.i = i == null ? null : i.trim();
    }
}