package com.kaige123.daomu.DAO.Bean;

public class ResourceDownload {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourcedownload.rdid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long rdid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourcedownload.rdtitle
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String rdtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourcedownload.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long vcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourcedownload.qnparamteter1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String qnparamteter1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourcedownload.qnparamteter2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String qnparamteter2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resourcedownload.qnparamteter3
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String qnparamteter3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourcedownload.rdid
     *
     * @return the value of resourcedownload.rdid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getRdid() {
        return rdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourcedownload.rdid
     *
     * @param rdid the value for resourcedownload.rdid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setRdid(Long rdid) {
        this.rdid = rdid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourcedownload.rdtitle
     *
     * @return the value of resourcedownload.rdtitle
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getRdtitle() {
        return rdtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourcedownload.rdtitle
     *
     * @param rdtitle the value for resourcedownload.rdtitle
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setRdtitle(String rdtitle) {
        this.rdtitle = rdtitle == null ? null : rdtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourcedownload.vcid
     *
     * @return the value of resourcedownload.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getVcid() {
        return vcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourcedownload.vcid
     *
     * @param vcid the value for resourcedownload.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVcid(Long vcid) {
        this.vcid = vcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourcedownload.qnparamteter1
     *
     * @return the value of resourcedownload.qnparamteter1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getQnparamteter1() {
        return qnparamteter1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourcedownload.qnparamteter1
     *
     * @param qnparamteter1 the value for resourcedownload.qnparamteter1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setQnparamteter1(String qnparamteter1) {
        this.qnparamteter1 = qnparamteter1 == null ? null : qnparamteter1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourcedownload.qnparamteter2
     *
     * @return the value of resourcedownload.qnparamteter2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getQnparamteter2() {
        return qnparamteter2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourcedownload.qnparamteter2
     *
     * @param qnparamteter2 the value for resourcedownload.qnparamteter2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setQnparamteter2(String qnparamteter2) {
        this.qnparamteter2 = qnparamteter2 == null ? null : qnparamteter2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resourcedownload.qnparamteter3
     *
     * @return the value of resourcedownload.qnparamteter3
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getQnparamteter3() {
        return qnparamteter3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resourcedownload.qnparamteter3
     *
     * @param qnparamteter3 the value for resourcedownload.qnparamteter3
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setQnparamteter3(String qnparamteter3) {
        this.qnparamteter3 = qnparamteter3 == null ? null : qnparamteter3.trim();
    }
}