package com.kaige123.daomu.DAO.Bean;

import java.util.ArrayList;
import java.util.List;

public class ResourceDownloadExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public ResourceDownloadExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRdidIsNull() {
            addCriterion("rdid is null");
            return (Criteria) this;
        }

        public Criteria andRdidIsNotNull() {
            addCriterion("rdid is not null");
            return (Criteria) this;
        }

        public Criteria andRdidEqualTo(Long value) {
            addCriterion("rdid =", value, "rdid");
            return (Criteria) this;
        }

        public Criteria andRdidNotEqualTo(Long value) {
            addCriterion("rdid <>", value, "rdid");
            return (Criteria) this;
        }

        public Criteria andRdidGreaterThan(Long value) {
            addCriterion("rdid >", value, "rdid");
            return (Criteria) this;
        }

        public Criteria andRdidGreaterThanOrEqualTo(Long value) {
            addCriterion("rdid >=", value, "rdid");
            return (Criteria) this;
        }

        public Criteria andRdidLessThan(Long value) {
            addCriterion("rdid <", value, "rdid");
            return (Criteria) this;
        }

        public Criteria andRdidLessThanOrEqualTo(Long value) {
            addCriterion("rdid <=", value, "rdid");
            return (Criteria) this;
        }

        public Criteria andRdidIn(List<Long> values) {
            addCriterion("rdid in", values, "rdid");
            return (Criteria) this;
        }

        public Criteria andRdidNotIn(List<Long> values) {
            addCriterion("rdid not in", values, "rdid");
            return (Criteria) this;
        }

        public Criteria andRdidBetween(Long value1, Long value2) {
            addCriterion("rdid between", value1, value2, "rdid");
            return (Criteria) this;
        }

        public Criteria andRdidNotBetween(Long value1, Long value2) {
            addCriterion("rdid not between", value1, value2, "rdid");
            return (Criteria) this;
        }

        public Criteria andRdtitleIsNull() {
            addCriterion("rdtitle is null");
            return (Criteria) this;
        }

        public Criteria andRdtitleIsNotNull() {
            addCriterion("rdtitle is not null");
            return (Criteria) this;
        }

        public Criteria andRdtitleEqualTo(String value) {
            addCriterion("rdtitle =", value, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleNotEqualTo(String value) {
            addCriterion("rdtitle <>", value, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleGreaterThan(String value) {
            addCriterion("rdtitle >", value, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleGreaterThanOrEqualTo(String value) {
            addCriterion("rdtitle >=", value, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleLessThan(String value) {
            addCriterion("rdtitle <", value, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleLessThanOrEqualTo(String value) {
            addCriterion("rdtitle <=", value, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleLike(String value) {
            addCriterion("rdtitle like", value, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleNotLike(String value) {
            addCriterion("rdtitle not like", value, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleIn(List<String> values) {
            addCriterion("rdtitle in", values, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleNotIn(List<String> values) {
            addCriterion("rdtitle not in", values, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleBetween(String value1, String value2) {
            addCriterion("rdtitle between", value1, value2, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andRdtitleNotBetween(String value1, String value2) {
            addCriterion("rdtitle not between", value1, value2, "rdtitle");
            return (Criteria) this;
        }

        public Criteria andVcidIsNull() {
            addCriterion("vcid is null");
            return (Criteria) this;
        }

        public Criteria andVcidIsNotNull() {
            addCriterion("vcid is not null");
            return (Criteria) this;
        }

        public Criteria andVcidEqualTo(Long value) {
            addCriterion("vcid =", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidNotEqualTo(Long value) {
            addCriterion("vcid <>", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidGreaterThan(Long value) {
            addCriterion("vcid >", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidGreaterThanOrEqualTo(Long value) {
            addCriterion("vcid >=", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidLessThan(Long value) {
            addCriterion("vcid <", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidLessThanOrEqualTo(Long value) {
            addCriterion("vcid <=", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidIn(List<Long> values) {
            addCriterion("vcid in", values, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidNotIn(List<Long> values) {
            addCriterion("vcid not in", values, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidBetween(Long value1, Long value2) {
            addCriterion("vcid between", value1, value2, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidNotBetween(Long value1, Long value2) {
            addCriterion("vcid not between", value1, value2, "vcid");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1IsNull() {
            addCriterion("qnparamteter1 is null");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1IsNotNull() {
            addCriterion("qnparamteter1 is not null");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1EqualTo(String value) {
            addCriterion("qnparamteter1 =", value, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1NotEqualTo(String value) {
            addCriterion("qnparamteter1 <>", value, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1GreaterThan(String value) {
            addCriterion("qnparamteter1 >", value, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1GreaterThanOrEqualTo(String value) {
            addCriterion("qnparamteter1 >=", value, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1LessThan(String value) {
            addCriterion("qnparamteter1 <", value, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1LessThanOrEqualTo(String value) {
            addCriterion("qnparamteter1 <=", value, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1Like(String value) {
            addCriterion("qnparamteter1 like", value, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1NotLike(String value) {
            addCriterion("qnparamteter1 not like", value, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1In(List<String> values) {
            addCriterion("qnparamteter1 in", values, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1NotIn(List<String> values) {
            addCriterion("qnparamteter1 not in", values, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1Between(String value1, String value2) {
            addCriterion("qnparamteter1 between", value1, value2, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter1NotBetween(String value1, String value2) {
            addCriterion("qnparamteter1 not between", value1, value2, "qnparamteter1");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2IsNull() {
            addCriterion("qnparamteter2 is null");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2IsNotNull() {
            addCriterion("qnparamteter2 is not null");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2EqualTo(String value) {
            addCriterion("qnparamteter2 =", value, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2NotEqualTo(String value) {
            addCriterion("qnparamteter2 <>", value, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2GreaterThan(String value) {
            addCriterion("qnparamteter2 >", value, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2GreaterThanOrEqualTo(String value) {
            addCriterion("qnparamteter2 >=", value, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2LessThan(String value) {
            addCriterion("qnparamteter2 <", value, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2LessThanOrEqualTo(String value) {
            addCriterion("qnparamteter2 <=", value, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2Like(String value) {
            addCriterion("qnparamteter2 like", value, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2NotLike(String value) {
            addCriterion("qnparamteter2 not like", value, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2In(List<String> values) {
            addCriterion("qnparamteter2 in", values, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2NotIn(List<String> values) {
            addCriterion("qnparamteter2 not in", values, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2Between(String value1, String value2) {
            addCriterion("qnparamteter2 between", value1, value2, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter2NotBetween(String value1, String value2) {
            addCriterion("qnparamteter2 not between", value1, value2, "qnparamteter2");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3IsNull() {
            addCriterion("qnparamteter3 is null");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3IsNotNull() {
            addCriterion("qnparamteter3 is not null");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3EqualTo(String value) {
            addCriterion("qnparamteter3 =", value, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3NotEqualTo(String value) {
            addCriterion("qnparamteter3 <>", value, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3GreaterThan(String value) {
            addCriterion("qnparamteter3 >", value, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3GreaterThanOrEqualTo(String value) {
            addCriterion("qnparamteter3 >=", value, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3LessThan(String value) {
            addCriterion("qnparamteter3 <", value, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3LessThanOrEqualTo(String value) {
            addCriterion("qnparamteter3 <=", value, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3Like(String value) {
            addCriterion("qnparamteter3 like", value, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3NotLike(String value) {
            addCriterion("qnparamteter3 not like", value, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3In(List<String> values) {
            addCriterion("qnparamteter3 in", values, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3NotIn(List<String> values) {
            addCriterion("qnparamteter3 not in", values, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3Between(String value1, String value2) {
            addCriterion("qnparamteter3 between", value1, value2, "qnparamteter3");
            return (Criteria) this;
        }

        public Criteria andQnparamteter3NotBetween(String value1, String value2) {
            addCriterion("qnparamteter3 not between", value1, value2, "qnparamteter3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resourcedownload
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 13 11:12:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resourcedownload
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}