package com.kaige123.daomu.DAO.Bean;

import java.util.Date;

public class Userlog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.ulid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String ulid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.logintime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Date logintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.loginIp
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String loginip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.loginProvince
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String loginprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userlog.loginCity
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String logincity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.ulid
     *
     * @return the value of userlog.ulid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getUlid() {
        return ulid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.ulid
     *
     * @param ulid the value for userlog.ulid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setUlid(String ulid) {
        this.ulid = ulid == null ? null : ulid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.uid
     *
     * @return the value of userlog.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.uid
     *
     * @param uid the value for userlog.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.logintime
     *
     * @return the value of userlog.logintime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Date getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.logintime
     *
     * @param logintime the value for userlog.logintime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setLogintime(Date logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.loginIp
     *
     * @return the value of userlog.loginIp
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.loginIp
     *
     * @param loginip the value for userlog.loginIp
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip == null ? null : loginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.loginProvince
     *
     * @return the value of userlog.loginProvince
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getLoginprovince() {
        return loginprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.loginProvince
     *
     * @param loginprovince the value for userlog.loginProvince
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setLoginprovince(String loginprovince) {
        this.loginprovince = loginprovince == null ? null : loginprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userlog.loginCity
     *
     * @return the value of userlog.loginCity
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getLogincity() {
        return logincity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userlog.loginCity
     *
     * @param logincity the value for userlog.loginCity
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setLogincity(String logincity) {
        this.logincity = logincity == null ? null : logincity.trim();
    }
}