package com.kaige123.daomu.DAO.Bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Long value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Long value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Long value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Long value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Long value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Long value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Long> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Long> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Long value1, Long value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Long value1, Long value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidIsNull() {
            addCriterion("recommendUid is null");
            return (Criteria) this;
        }

        public Criteria andRecommenduidIsNotNull() {
            addCriterion("recommendUid is not null");
            return (Criteria) this;
        }

        public Criteria andRecommenduidEqualTo(String value) {
            addCriterion("recommendUid =", value, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidNotEqualTo(String value) {
            addCriterion("recommendUid <>", value, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidGreaterThan(String value) {
            addCriterion("recommendUid >", value, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidGreaterThanOrEqualTo(String value) {
            addCriterion("recommendUid >=", value, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidLessThan(String value) {
            addCriterion("recommendUid <", value, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidLessThanOrEqualTo(String value) {
            addCriterion("recommendUid <=", value, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidLike(String value) {
            addCriterion("recommendUid like", value, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidNotLike(String value) {
            addCriterion("recommendUid not like", value, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidIn(List<String> values) {
            addCriterion("recommendUid in", values, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidNotIn(List<String> values) {
            addCriterion("recommendUid not in", values, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidBetween(String value1, String value2) {
            addCriterion("recommendUid between", value1, value2, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andRecommenduidNotBetween(String value1, String value2) {
            addCriterion("recommendUid not between", value1, value2, "recommenduid");
            return (Criteria) this;
        }

        public Criteria andMonyIsNull() {
            addCriterion("mony is null");
            return (Criteria) this;
        }

        public Criteria andMonyIsNotNull() {
            addCriterion("mony is not null");
            return (Criteria) this;
        }

        public Criteria andMonyEqualTo(Long value) {
            addCriterion("mony =", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyNotEqualTo(Long value) {
            addCriterion("mony <>", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyGreaterThan(Long value) {
            addCriterion("mony >", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyGreaterThanOrEqualTo(Long value) {
            addCriterion("mony >=", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyLessThan(Long value) {
            addCriterion("mony <", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyLessThanOrEqualTo(Long value) {
            addCriterion("mony <=", value, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyIn(List<Long> values) {
            addCriterion("mony in", values, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyNotIn(List<Long> values) {
            addCriterion("mony not in", values, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyBetween(Long value1, Long value2) {
            addCriterion("mony between", value1, value2, "mony");
            return (Criteria) this;
        }

        public Criteria andMonyNotBetween(Long value1, Long value2) {
            addCriterion("mony not between", value1, value2, "mony");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickName is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickName is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickName =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickName <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickName >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickName >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickName <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickName <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickName like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickName not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickName in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickName not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickName between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickName not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andIdentifyIsNull() {
            addCriterion("identify is null");
            return (Criteria) this;
        }

        public Criteria andIdentifyIsNotNull() {
            addCriterion("identify is not null");
            return (Criteria) this;
        }

        public Criteria andIdentifyEqualTo(String value) {
            addCriterion("identify =", value, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyNotEqualTo(String value) {
            addCriterion("identify <>", value, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyGreaterThan(String value) {
            addCriterion("identify >", value, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyGreaterThanOrEqualTo(String value) {
            addCriterion("identify >=", value, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyLessThan(String value) {
            addCriterion("identify <", value, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyLessThanOrEqualTo(String value) {
            addCriterion("identify <=", value, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyLike(String value) {
            addCriterion("identify like", value, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyNotLike(String value) {
            addCriterion("identify not like", value, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyIn(List<String> values) {
            addCriterion("identify in", values, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyNotIn(List<String> values) {
            addCriterion("identify not in", values, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyBetween(String value1, String value2) {
            addCriterion("identify between", value1, value2, "identify");
            return (Criteria) this;
        }

        public Criteria andIdentifyNotBetween(String value1, String value2) {
            addCriterion("identify not between", value1, value2, "identify");
            return (Criteria) this;
        }

        public Criteria andPaypasswordIsNull() {
            addCriterion("payPassword is null");
            return (Criteria) this;
        }

        public Criteria andPaypasswordIsNotNull() {
            addCriterion("payPassword is not null");
            return (Criteria) this;
        }

        public Criteria andPaypasswordEqualTo(String value) {
            addCriterion("payPassword =", value, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordNotEqualTo(String value) {
            addCriterion("payPassword <>", value, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordGreaterThan(String value) {
            addCriterion("payPassword >", value, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordGreaterThanOrEqualTo(String value) {
            addCriterion("payPassword >=", value, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordLessThan(String value) {
            addCriterion("payPassword <", value, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordLessThanOrEqualTo(String value) {
            addCriterion("payPassword <=", value, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordLike(String value) {
            addCriterion("payPassword like", value, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordNotLike(String value) {
            addCriterion("payPassword not like", value, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordIn(List<String> values) {
            addCriterion("payPassword in", values, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordNotIn(List<String> values) {
            addCriterion("payPassword not in", values, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordBetween(String value1, String value2) {
            addCriterion("payPassword between", value1, value2, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPaypasswordNotBetween(String value1, String value2) {
            addCriterion("payPassword not between", value1, value2, "paypassword");
            return (Criteria) this;
        }

        public Criteria andPassswordIsNull() {
            addCriterion("passsword is null");
            return (Criteria) this;
        }

        public Criteria andPassswordIsNotNull() {
            addCriterion("passsword is not null");
            return (Criteria) this;
        }

        public Criteria andPassswordEqualTo(String value) {
            addCriterion("passsword =", value, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordNotEqualTo(String value) {
            addCriterion("passsword <>", value, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordGreaterThan(String value) {
            addCriterion("passsword >", value, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordGreaterThanOrEqualTo(String value) {
            addCriterion("passsword >=", value, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordLessThan(String value) {
            addCriterion("passsword <", value, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordLessThanOrEqualTo(String value) {
            addCriterion("passsword <=", value, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordLike(String value) {
            addCriterion("passsword like", value, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordNotLike(String value) {
            addCriterion("passsword not like", value, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordIn(List<String> values) {
            addCriterion("passsword in", values, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordNotIn(List<String> values) {
            addCriterion("passsword not in", values, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordBetween(String value1, String value2) {
            addCriterion("passsword between", value1, value2, "passsword");
            return (Criteria) this;
        }

        public Criteria andPassswordNotBetween(String value1, String value2) {
            addCriterion("passsword not between", value1, value2, "passsword");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("openid is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("openid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("openid =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("openid <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("openid >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("openid >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("openid <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("openid <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("openid like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("openid not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("openid in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("openid not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("openid between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("openid not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("createDate is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("createDate is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("createDate =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("createDate <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("createDate >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("createDate >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("createDate <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("createDate <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("createDate in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("createDate not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("createDate between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("createDate not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andLastlogindateIsNull() {
            addCriterion("lastLoginDate is null");
            return (Criteria) this;
        }

        public Criteria andLastlogindateIsNotNull() {
            addCriterion("lastLoginDate is not null");
            return (Criteria) this;
        }

        public Criteria andLastlogindateEqualTo(Date value) {
            addCriterion("lastLoginDate =", value, "lastlogindate");
            return (Criteria) this;
        }

        public Criteria andLastlogindateNotEqualTo(Date value) {
            addCriterion("lastLoginDate <>", value, "lastlogindate");
            return (Criteria) this;
        }

        public Criteria andLastlogindateGreaterThan(Date value) {
            addCriterion("lastLoginDate >", value, "lastlogindate");
            return (Criteria) this;
        }

        public Criteria andLastlogindateGreaterThanOrEqualTo(Date value) {
            addCriterion("lastLoginDate >=", value, "lastlogindate");
            return (Criteria) this;
        }

        public Criteria andLastlogindateLessThan(Date value) {
            addCriterion("lastLoginDate <", value, "lastlogindate");
            return (Criteria) this;
        }

        public Criteria andLastlogindateLessThanOrEqualTo(Date value) {
            addCriterion("lastLoginDate <=", value, "lastlogindate");
            return (Criteria) this;
        }

        public Criteria andLastlogindateIn(List<Date> values) {
            addCriterion("lastLoginDate in", values, "lastlogindate");
            return (Criteria) this;
        }

        public Criteria andLastlogindateNotIn(List<Date> values) {
            addCriterion("lastLoginDate not in", values, "lastlogindate");
            return (Criteria) this;
        }

        public Criteria andLastlogindateBetween(Date value1, Date value2) {
            addCriterion("lastLoginDate between", value1, value2, "lastlogindate");
            return (Criteria) this;
        }

        public Criteria andLastlogindateNotBetween(Date value1, Date value2) {
            addCriterion("lastLoginDate not between", value1, value2, "lastlogindate");
            return (Criteria) this;
        }

        public Criteria andHeadimgIsNull() {
            addCriterion("headimg is null");
            return (Criteria) this;
        }

        public Criteria andHeadimgIsNotNull() {
            addCriterion("headimg is not null");
            return (Criteria) this;
        }

        public Criteria andHeadimgEqualTo(String value) {
            addCriterion("headimg =", value, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgNotEqualTo(String value) {
            addCriterion("headimg <>", value, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgGreaterThan(String value) {
            addCriterion("headimg >", value, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgGreaterThanOrEqualTo(String value) {
            addCriterion("headimg >=", value, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgLessThan(String value) {
            addCriterion("headimg <", value, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgLessThanOrEqualTo(String value) {
            addCriterion("headimg <=", value, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgLike(String value) {
            addCriterion("headimg like", value, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgNotLike(String value) {
            addCriterion("headimg not like", value, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgIn(List<String> values) {
            addCriterion("headimg in", values, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgNotIn(List<String> values) {
            addCriterion("headimg not in", values, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgBetween(String value1, String value2) {
            addCriterion("headimg between", value1, value2, "headimg");
            return (Criteria) this;
        }

        public Criteria andHeadimgNotBetween(String value1, String value2) {
            addCriterion("headimg not between", value1, value2, "headimg");
            return (Criteria) this;
        }

        public Criteria andLoginaddressIsNull() {
            addCriterion("loginAddress is null");
            return (Criteria) this;
        }

        public Criteria andLoginaddressIsNotNull() {
            addCriterion("loginAddress is not null");
            return (Criteria) this;
        }

        public Criteria andLoginaddressEqualTo(String value) {
            addCriterion("loginAddress =", value, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressNotEqualTo(String value) {
            addCriterion("loginAddress <>", value, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressGreaterThan(String value) {
            addCriterion("loginAddress >", value, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressGreaterThanOrEqualTo(String value) {
            addCriterion("loginAddress >=", value, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressLessThan(String value) {
            addCriterion("loginAddress <", value, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressLessThanOrEqualTo(String value) {
            addCriterion("loginAddress <=", value, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressLike(String value) {
            addCriterion("loginAddress like", value, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressNotLike(String value) {
            addCriterion("loginAddress not like", value, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressIn(List<String> values) {
            addCriterion("loginAddress in", values, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressNotIn(List<String> values) {
            addCriterion("loginAddress not in", values, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressBetween(String value1, String value2) {
            addCriterion("loginAddress between", value1, value2, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginaddressNotBetween(String value1, String value2) {
            addCriterion("loginAddress not between", value1, value2, "loginaddress");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberIsNull() {
            addCriterion("loginErrorNumber is null");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberIsNotNull() {
            addCriterion("loginErrorNumber is not null");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberEqualTo(Integer value) {
            addCriterion("loginErrorNumber =", value, "loginerrornumber");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberNotEqualTo(Integer value) {
            addCriterion("loginErrorNumber <>", value, "loginerrornumber");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberGreaterThan(Integer value) {
            addCriterion("loginErrorNumber >", value, "loginerrornumber");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("loginErrorNumber >=", value, "loginerrornumber");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberLessThan(Integer value) {
            addCriterion("loginErrorNumber <", value, "loginerrornumber");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberLessThanOrEqualTo(Integer value) {
            addCriterion("loginErrorNumber <=", value, "loginerrornumber");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberIn(List<Integer> values) {
            addCriterion("loginErrorNumber in", values, "loginerrornumber");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberNotIn(List<Integer> values) {
            addCriterion("loginErrorNumber not in", values, "loginerrornumber");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberBetween(Integer value1, Integer value2) {
            addCriterion("loginErrorNumber between", value1, value2, "loginerrornumber");
            return (Criteria) this;
        }

        public Criteria andLoginerrornumberNotBetween(Integer value1, Integer value2) {
            addCriterion("loginErrorNumber not between", value1, value2, "loginerrornumber");
            return (Criteria) this;
        }

        public Criteria andLockstateIsNull() {
            addCriterion("lockState is null");
            return (Criteria) this;
        }

        public Criteria andLockstateIsNotNull() {
            addCriterion("lockState is not null");
            return (Criteria) this;
        }

        public Criteria andLockstateEqualTo(String value) {
            addCriterion("lockState =", value, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateNotEqualTo(String value) {
            addCriterion("lockState <>", value, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateGreaterThan(String value) {
            addCriterion("lockState >", value, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateGreaterThanOrEqualTo(String value) {
            addCriterion("lockState >=", value, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateLessThan(String value) {
            addCriterion("lockState <", value, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateLessThanOrEqualTo(String value) {
            addCriterion("lockState <=", value, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateLike(String value) {
            addCriterion("lockState like", value, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateNotLike(String value) {
            addCriterion("lockState not like", value, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateIn(List<String> values) {
            addCriterion("lockState in", values, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateNotIn(List<String> values) {
            addCriterion("lockState not in", values, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateBetween(String value1, String value2) {
            addCriterion("lockState between", value1, value2, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockstateNotBetween(String value1, String value2) {
            addCriterion("lockState not between", value1, value2, "lockstate");
            return (Criteria) this;
        }

        public Criteria andLockdateIsNull() {
            addCriterion("lockDate is null");
            return (Criteria) this;
        }

        public Criteria andLockdateIsNotNull() {
            addCriterion("lockDate is not null");
            return (Criteria) this;
        }

        public Criteria andLockdateEqualTo(Date value) {
            addCriterion("lockDate =", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateNotEqualTo(Date value) {
            addCriterion("lockDate <>", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateGreaterThan(Date value) {
            addCriterion("lockDate >", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateGreaterThanOrEqualTo(Date value) {
            addCriterion("lockDate >=", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateLessThan(Date value) {
            addCriterion("lockDate <", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateLessThanOrEqualTo(Date value) {
            addCriterion("lockDate <=", value, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateIn(List<Date> values) {
            addCriterion("lockDate in", values, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateNotIn(List<Date> values) {
            addCriterion("lockDate not in", values, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateBetween(Date value1, Date value2) {
            addCriterion("lockDate between", value1, value2, "lockdate");
            return (Criteria) this;
        }

        public Criteria andLockdateNotBetween(Date value1, Date value2) {
            addCriterion("lockDate not between", value1, value2, "lockdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 13 11:12:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}