package com.kaige123.daomu.DAO.Bean;

import java.util.Date;

public class Vcomment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcomment.vmid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long vmid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcomment.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcomment.vice
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long vice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcomment.commentText
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String commenttext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcomment.commentDate
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Date commentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcomment.Star
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Integer star;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcomment.vmid
     *
     * @return the value of vcomment.vmid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getVmid() {
        return vmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcomment.vmid
     *
     * @param vmid the value for vcomment.vmid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVmid(Long vmid) {
        this.vmid = vmid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcomment.uid
     *
     * @return the value of vcomment.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcomment.uid
     *
     * @param uid the value for vcomment.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcomment.vice
     *
     * @return the value of vcomment.vice
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getVice() {
        return vice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcomment.vice
     *
     * @param vice the value for vcomment.vice
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVice(Long vice) {
        this.vice = vice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcomment.commentText
     *
     * @return the value of vcomment.commentText
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getCommenttext() {
        return commenttext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcomment.commentText
     *
     * @param commenttext the value for vcomment.commentText
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setCommenttext(String commenttext) {
        this.commenttext = commenttext == null ? null : commenttext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcomment.commentDate
     *
     * @return the value of vcomment.commentDate
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Date getCommentdate() {
        return commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcomment.commentDate
     *
     * @param commentdate the value for vcomment.commentDate
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setCommentdate(Date commentdate) {
        this.commentdate = commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcomment.Star
     *
     * @return the value of vcomment.Star
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Integer getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcomment.Star
     *
     * @param star the value for vcomment.Star
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setStar(Integer star) {
        this.star = star;
    }
}