package com.kaige123.daomu.DAO.Bean;

import java.math.BigDecimal;
import java.util.Date;

public class Videobuyorder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.oid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long vcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.createOrderDate
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String createorderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.ThridPartyorderNumber
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Date thridpartyordernumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.payOverDate
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Date payoverdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.payType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String paytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.payMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private BigDecimal paymony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.Rreferee1Uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long rreferee1uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.mony1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private BigDecimal mony1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.Rreferee2Uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long rreferee2uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.mony2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private BigDecimal mony2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videobuyorder.BeLeftOverMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private BigDecimal beleftovermony;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.oid
     *
     * @return the value of videobuyorder.oid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.oid
     *
     * @param oid the value for videobuyorder.oid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.uid
     *
     * @return the value of videobuyorder.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.uid
     *
     * @param uid the value for videobuyorder.uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.vcid
     *
     * @return the value of videobuyorder.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getVcid() {
        return vcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.vcid
     *
     * @param vcid the value for videobuyorder.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVcid(Long vcid) {
        this.vcid = vcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.createOrderDate
     *
     * @return the value of videobuyorder.createOrderDate
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getCreateorderdate() {
        return createorderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.createOrderDate
     *
     * @param createorderdate the value for videobuyorder.createOrderDate
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setCreateorderdate(String createorderdate) {
        this.createorderdate = createorderdate == null ? null : createorderdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.ThridPartyorderNumber
     *
     * @return the value of videobuyorder.ThridPartyorderNumber
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Date getThridpartyordernumber() {
        return thridpartyordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.ThridPartyorderNumber
     *
     * @param thridpartyordernumber the value for videobuyorder.ThridPartyorderNumber
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setThridpartyordernumber(Date thridpartyordernumber) {
        this.thridpartyordernumber = thridpartyordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.payOverDate
     *
     * @return the value of videobuyorder.payOverDate
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Date getPayoverdate() {
        return payoverdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.payOverDate
     *
     * @param payoverdate the value for videobuyorder.payOverDate
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setPayoverdate(Date payoverdate) {
        this.payoverdate = payoverdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.payType
     *
     * @return the value of videobuyorder.payType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.payType
     *
     * @param paytype the value for videobuyorder.payType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setPaytype(String paytype) {
        this.paytype = paytype == null ? null : paytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.payMony
     *
     * @return the value of videobuyorder.payMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public BigDecimal getPaymony() {
        return paymony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.payMony
     *
     * @param paymony the value for videobuyorder.payMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setPaymony(BigDecimal paymony) {
        this.paymony = paymony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.Rreferee1Uid
     *
     * @return the value of videobuyorder.Rreferee1Uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getRreferee1uid() {
        return rreferee1uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.Rreferee1Uid
     *
     * @param rreferee1uid the value for videobuyorder.Rreferee1Uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setRreferee1uid(Long rreferee1uid) {
        this.rreferee1uid = rreferee1uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.mony1
     *
     * @return the value of videobuyorder.mony1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public BigDecimal getMony1() {
        return mony1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.mony1
     *
     * @param mony1 the value for videobuyorder.mony1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setMony1(BigDecimal mony1) {
        this.mony1 = mony1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.Rreferee2Uid
     *
     * @return the value of videobuyorder.Rreferee2Uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getRreferee2uid() {
        return rreferee2uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.Rreferee2Uid
     *
     * @param rreferee2uid the value for videobuyorder.Rreferee2Uid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setRreferee2uid(Long rreferee2uid) {
        this.rreferee2uid = rreferee2uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.mony2
     *
     * @return the value of videobuyorder.mony2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public BigDecimal getMony2() {
        return mony2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.mony2
     *
     * @param mony2 the value for videobuyorder.mony2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setMony2(BigDecimal mony2) {
        this.mony2 = mony2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videobuyorder.BeLeftOverMony
     *
     * @return the value of videobuyorder.BeLeftOverMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public BigDecimal getBeleftovermony() {
        return beleftovermony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videobuyorder.BeLeftOverMony
     *
     * @param beleftovermony the value for videobuyorder.BeLeftOverMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setBeleftovermony(BigDecimal beleftovermony) {
        this.beleftovermony = beleftovermony;
    }
}