package com.kaige123.daomu.DAO.Bean;

import java.math.BigDecimal;

public class Videocoures {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long vcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.vcTitle
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String vctitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.vtid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long vtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.vcDescription
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String vcdescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.HeadImg
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String headimg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.vcimg1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String vcimg1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.vcimg2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String vcimg2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.vcimg3
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String vcimg3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.userSeeType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String userseetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.FullMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private BigDecimal fullmony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.VIPMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private BigDecimal vipmony;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.ShareMony1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private BigDecimal sharemony1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.ShareMony2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private BigDecimal sharemony2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videocoures.SaleNumber
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Integer salenumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.vcid
     *
     * @return the value of videocoures.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getVcid() {
        return vcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.vcid
     *
     * @param vcid the value for videocoures.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVcid(Long vcid) {
        this.vcid = vcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.vcTitle
     *
     * @return the value of videocoures.vcTitle
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getVctitle() {
        return vctitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.vcTitle
     *
     * @param vctitle the value for videocoures.vcTitle
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVctitle(String vctitle) {
        this.vctitle = vctitle == null ? null : vctitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.vtid
     *
     * @return the value of videocoures.vtid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getVtid() {
        return vtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.vtid
     *
     * @param vtid the value for videocoures.vtid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVtid(Long vtid) {
        this.vtid = vtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.vcDescription
     *
     * @return the value of videocoures.vcDescription
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getVcdescription() {
        return vcdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.vcDescription
     *
     * @param vcdescription the value for videocoures.vcDescription
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVcdescription(String vcdescription) {
        this.vcdescription = vcdescription == null ? null : vcdescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.HeadImg
     *
     * @return the value of videocoures.HeadImg
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getHeadimg() {
        return headimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.HeadImg
     *
     * @param headimg the value for videocoures.HeadImg
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setHeadimg(String headimg) {
        this.headimg = headimg == null ? null : headimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.vcimg1
     *
     * @return the value of videocoures.vcimg1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getVcimg1() {
        return vcimg1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.vcimg1
     *
     * @param vcimg1 the value for videocoures.vcimg1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVcimg1(String vcimg1) {
        this.vcimg1 = vcimg1 == null ? null : vcimg1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.vcimg2
     *
     * @return the value of videocoures.vcimg2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getVcimg2() {
        return vcimg2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.vcimg2
     *
     * @param vcimg2 the value for videocoures.vcimg2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVcimg2(String vcimg2) {
        this.vcimg2 = vcimg2 == null ? null : vcimg2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.vcimg3
     *
     * @return the value of videocoures.vcimg3
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getVcimg3() {
        return vcimg3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.vcimg3
     *
     * @param vcimg3 the value for videocoures.vcimg3
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVcimg3(String vcimg3) {
        this.vcimg3 = vcimg3 == null ? null : vcimg3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.userSeeType
     *
     * @return the value of videocoures.userSeeType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getUserseetype() {
        return userseetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.userSeeType
     *
     * @param userseetype the value for videocoures.userSeeType
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setUserseetype(String userseetype) {
        this.userseetype = userseetype == null ? null : userseetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.FullMony
     *
     * @return the value of videocoures.FullMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public BigDecimal getFullmony() {
        return fullmony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.FullMony
     *
     * @param fullmony the value for videocoures.FullMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setFullmony(BigDecimal fullmony) {
        this.fullmony = fullmony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.VIPMony
     *
     * @return the value of videocoures.VIPMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public BigDecimal getVipmony() {
        return vipmony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.VIPMony
     *
     * @param vipmony the value for videocoures.VIPMony
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVipmony(BigDecimal vipmony) {
        this.vipmony = vipmony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.ShareMony1
     *
     * @return the value of videocoures.ShareMony1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public BigDecimal getSharemony1() {
        return sharemony1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.ShareMony1
     *
     * @param sharemony1 the value for videocoures.ShareMony1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setSharemony1(BigDecimal sharemony1) {
        this.sharemony1 = sharemony1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.ShareMony2
     *
     * @return the value of videocoures.ShareMony2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public BigDecimal getSharemony2() {
        return sharemony2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.ShareMony2
     *
     * @param sharemony2 the value for videocoures.ShareMony2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setSharemony2(BigDecimal sharemony2) {
        this.sharemony2 = sharemony2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videocoures.SaleNumber
     *
     * @return the value of videocoures.SaleNumber
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Integer getSalenumber() {
        return salenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videocoures.SaleNumber
     *
     * @param salenumber the value for videocoures.SaleNumber
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setSalenumber(Integer salenumber) {
        this.salenumber = salenumber;
    }
}