package com.kaige123.daomu.DAO.Bean;

import java.util.ArrayList;
import java.util.List;

public class VideoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public VideoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVidIsNull() {
            addCriterion("vid is null");
            return (Criteria) this;
        }

        public Criteria andVidIsNotNull() {
            addCriterion("vid is not null");
            return (Criteria) this;
        }

        public Criteria andVidEqualTo(Long value) {
            addCriterion("vid =", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotEqualTo(Long value) {
            addCriterion("vid <>", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThan(Long value) {
            addCriterion("vid >", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidGreaterThanOrEqualTo(Long value) {
            addCriterion("vid >=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThan(Long value) {
            addCriterion("vid <", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidLessThanOrEqualTo(Long value) {
            addCriterion("vid <=", value, "vid");
            return (Criteria) this;
        }

        public Criteria andVidIn(List<Long> values) {
            addCriterion("vid in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotIn(List<Long> values) {
            addCriterion("vid not in", values, "vid");
            return (Criteria) this;
        }

        public Criteria andVidBetween(Long value1, Long value2) {
            addCriterion("vid between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andVidNotBetween(Long value1, Long value2) {
            addCriterion("vid not between", value1, value2, "vid");
            return (Criteria) this;
        }

        public Criteria andVcidIsNull() {
            addCriterion("vcid is null");
            return (Criteria) this;
        }

        public Criteria andVcidIsNotNull() {
            addCriterion("vcid is not null");
            return (Criteria) this;
        }

        public Criteria andVcidEqualTo(Long value) {
            addCriterion("vcid =", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidNotEqualTo(Long value) {
            addCriterion("vcid <>", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidGreaterThan(Long value) {
            addCriterion("vcid >", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidGreaterThanOrEqualTo(Long value) {
            addCriterion("vcid >=", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidLessThan(Long value) {
            addCriterion("vcid <", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidLessThanOrEqualTo(Long value) {
            addCriterion("vcid <=", value, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidIn(List<Long> values) {
            addCriterion("vcid in", values, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidNotIn(List<Long> values) {
            addCriterion("vcid not in", values, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidBetween(Long value1, Long value2) {
            addCriterion("vcid between", value1, value2, "vcid");
            return (Criteria) this;
        }

        public Criteria andVcidNotBetween(Long value1, Long value2) {
            addCriterion("vcid not between", value1, value2, "vcid");
            return (Criteria) this;
        }

        public Criteria andVtitleIsNull() {
            addCriterion("vtitle is null");
            return (Criteria) this;
        }

        public Criteria andVtitleIsNotNull() {
            addCriterion("vtitle is not null");
            return (Criteria) this;
        }

        public Criteria andVtitleEqualTo(String value) {
            addCriterion("vtitle =", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleNotEqualTo(String value) {
            addCriterion("vtitle <>", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleGreaterThan(String value) {
            addCriterion("vtitle >", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleGreaterThanOrEqualTo(String value) {
            addCriterion("vtitle >=", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleLessThan(String value) {
            addCriterion("vtitle <", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleLessThanOrEqualTo(String value) {
            addCriterion("vtitle <=", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleLike(String value) {
            addCriterion("vtitle like", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleNotLike(String value) {
            addCriterion("vtitle not like", value, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleIn(List<String> values) {
            addCriterion("vtitle in", values, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleNotIn(List<String> values) {
            addCriterion("vtitle not in", values, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleBetween(String value1, String value2) {
            addCriterion("vtitle between", value1, value2, "vtitle");
            return (Criteria) this;
        }

        public Criteria andVtitleNotBetween(String value1, String value2) {
            addCriterion("vtitle not between", value1, value2, "vtitle");
            return (Criteria) this;
        }

        public Criteria andCountdatemIsNull() {
            addCriterion("countDateM is null");
            return (Criteria) this;
        }

        public Criteria andCountdatemIsNotNull() {
            addCriterion("countDateM is not null");
            return (Criteria) this;
        }

        public Criteria andCountdatemEqualTo(Integer value) {
            addCriterion("countDateM =", value, "countdatem");
            return (Criteria) this;
        }

        public Criteria andCountdatemNotEqualTo(Integer value) {
            addCriterion("countDateM <>", value, "countdatem");
            return (Criteria) this;
        }

        public Criteria andCountdatemGreaterThan(Integer value) {
            addCriterion("countDateM >", value, "countdatem");
            return (Criteria) this;
        }

        public Criteria andCountdatemGreaterThanOrEqualTo(Integer value) {
            addCriterion("countDateM >=", value, "countdatem");
            return (Criteria) this;
        }

        public Criteria andCountdatemLessThan(Integer value) {
            addCriterion("countDateM <", value, "countdatem");
            return (Criteria) this;
        }

        public Criteria andCountdatemLessThanOrEqualTo(Integer value) {
            addCriterion("countDateM <=", value, "countdatem");
            return (Criteria) this;
        }

        public Criteria andCountdatemIn(List<Integer> values) {
            addCriterion("countDateM in", values, "countdatem");
            return (Criteria) this;
        }

        public Criteria andCountdatemNotIn(List<Integer> values) {
            addCriterion("countDateM not in", values, "countdatem");
            return (Criteria) this;
        }

        public Criteria andCountdatemBetween(Integer value1, Integer value2) {
            addCriterion("countDateM between", value1, value2, "countdatem");
            return (Criteria) this;
        }

        public Criteria andCountdatemNotBetween(Integer value1, Integer value2) {
            addCriterion("countDateM not between", value1, value2, "countdatem");
            return (Criteria) this;
        }

        public Criteria andFreetimeIsNull() {
            addCriterion("freeTime is null");
            return (Criteria) this;
        }

        public Criteria andFreetimeIsNotNull() {
            addCriterion("freeTime is not null");
            return (Criteria) this;
        }

        public Criteria andFreetimeEqualTo(Integer value) {
            addCriterion("freeTime =", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeNotEqualTo(Integer value) {
            addCriterion("freeTime <>", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeGreaterThan(Integer value) {
            addCriterion("freeTime >", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("freeTime >=", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeLessThan(Integer value) {
            addCriterion("freeTime <", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeLessThanOrEqualTo(Integer value) {
            addCriterion("freeTime <=", value, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeIn(List<Integer> values) {
            addCriterion("freeTime in", values, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeNotIn(List<Integer> values) {
            addCriterion("freeTime not in", values, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeBetween(Integer value1, Integer value2) {
            addCriterion("freeTime between", value1, value2, "freetime");
            return (Criteria) this;
        }

        public Criteria andFreetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("freeTime not between", value1, value2, "freetime");
            return (Criteria) this;
        }

        public Criteria andParamter1IsNull() {
            addCriterion("paramter1 is null");
            return (Criteria) this;
        }

        public Criteria andParamter1IsNotNull() {
            addCriterion("paramter1 is not null");
            return (Criteria) this;
        }

        public Criteria andParamter1EqualTo(String value) {
            addCriterion("paramter1 =", value, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1NotEqualTo(String value) {
            addCriterion("paramter1 <>", value, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1GreaterThan(String value) {
            addCriterion("paramter1 >", value, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1GreaterThanOrEqualTo(String value) {
            addCriterion("paramter1 >=", value, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1LessThan(String value) {
            addCriterion("paramter1 <", value, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1LessThanOrEqualTo(String value) {
            addCriterion("paramter1 <=", value, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1Like(String value) {
            addCriterion("paramter1 like", value, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1NotLike(String value) {
            addCriterion("paramter1 not like", value, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1In(List<String> values) {
            addCriterion("paramter1 in", values, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1NotIn(List<String> values) {
            addCriterion("paramter1 not in", values, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1Between(String value1, String value2) {
            addCriterion("paramter1 between", value1, value2, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter1NotBetween(String value1, String value2) {
            addCriterion("paramter1 not between", value1, value2, "paramter1");
            return (Criteria) this;
        }

        public Criteria andParamter2IsNull() {
            addCriterion("paramter2 is null");
            return (Criteria) this;
        }

        public Criteria andParamter2IsNotNull() {
            addCriterion("paramter2 is not null");
            return (Criteria) this;
        }

        public Criteria andParamter2EqualTo(String value) {
            addCriterion("paramter2 =", value, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2NotEqualTo(String value) {
            addCriterion("paramter2 <>", value, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2GreaterThan(String value) {
            addCriterion("paramter2 >", value, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2GreaterThanOrEqualTo(String value) {
            addCriterion("paramter2 >=", value, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2LessThan(String value) {
            addCriterion("paramter2 <", value, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2LessThanOrEqualTo(String value) {
            addCriterion("paramter2 <=", value, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2Like(String value) {
            addCriterion("paramter2 like", value, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2NotLike(String value) {
            addCriterion("paramter2 not like", value, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2In(List<String> values) {
            addCriterion("paramter2 in", values, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2NotIn(List<String> values) {
            addCriterion("paramter2 not in", values, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2Between(String value1, String value2) {
            addCriterion("paramter2 between", value1, value2, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter2NotBetween(String value1, String value2) {
            addCriterion("paramter2 not between", value1, value2, "paramter2");
            return (Criteria) this;
        }

        public Criteria andParamter3IsNull() {
            addCriterion("paramter3 is null");
            return (Criteria) this;
        }

        public Criteria andParamter3IsNotNull() {
            addCriterion("paramter3 is not null");
            return (Criteria) this;
        }

        public Criteria andParamter3EqualTo(String value) {
            addCriterion("paramter3 =", value, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3NotEqualTo(String value) {
            addCriterion("paramter3 <>", value, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3GreaterThan(String value) {
            addCriterion("paramter3 >", value, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3GreaterThanOrEqualTo(String value) {
            addCriterion("paramter3 >=", value, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3LessThan(String value) {
            addCriterion("paramter3 <", value, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3LessThanOrEqualTo(String value) {
            addCriterion("paramter3 <=", value, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3Like(String value) {
            addCriterion("paramter3 like", value, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3NotLike(String value) {
            addCriterion("paramter3 not like", value, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3In(List<String> values) {
            addCriterion("paramter3 in", values, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3NotIn(List<String> values) {
            addCriterion("paramter3 not in", values, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3Between(String value1, String value2) {
            addCriterion("paramter3 between", value1, value2, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter3NotBetween(String value1, String value2) {
            addCriterion("paramter3 not between", value1, value2, "paramter3");
            return (Criteria) this;
        }

        public Criteria andParamter4IsNull() {
            addCriterion("paramter4 is null");
            return (Criteria) this;
        }

        public Criteria andParamter4IsNotNull() {
            addCriterion("paramter4 is not null");
            return (Criteria) this;
        }

        public Criteria andParamter4EqualTo(String value) {
            addCriterion("paramter4 =", value, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4NotEqualTo(String value) {
            addCriterion("paramter4 <>", value, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4GreaterThan(String value) {
            addCriterion("paramter4 >", value, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4GreaterThanOrEqualTo(String value) {
            addCriterion("paramter4 >=", value, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4LessThan(String value) {
            addCriterion("paramter4 <", value, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4LessThanOrEqualTo(String value) {
            addCriterion("paramter4 <=", value, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4Like(String value) {
            addCriterion("paramter4 like", value, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4NotLike(String value) {
            addCriterion("paramter4 not like", value, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4In(List<String> values) {
            addCriterion("paramter4 in", values, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4NotIn(List<String> values) {
            addCriterion("paramter4 not in", values, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4Between(String value1, String value2) {
            addCriterion("paramter4 between", value1, value2, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter4NotBetween(String value1, String value2) {
            addCriterion("paramter4 not between", value1, value2, "paramter4");
            return (Criteria) this;
        }

        public Criteria andParamter5IsNull() {
            addCriterion("paramter5 is null");
            return (Criteria) this;
        }

        public Criteria andParamter5IsNotNull() {
            addCriterion("paramter5 is not null");
            return (Criteria) this;
        }

        public Criteria andParamter5EqualTo(String value) {
            addCriterion("paramter5 =", value, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5NotEqualTo(String value) {
            addCriterion("paramter5 <>", value, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5GreaterThan(String value) {
            addCriterion("paramter5 >", value, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5GreaterThanOrEqualTo(String value) {
            addCriterion("paramter5 >=", value, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5LessThan(String value) {
            addCriterion("paramter5 <", value, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5LessThanOrEqualTo(String value) {
            addCriterion("paramter5 <=", value, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5Like(String value) {
            addCriterion("paramter5 like", value, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5NotLike(String value) {
            addCriterion("paramter5 not like", value, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5In(List<String> values) {
            addCriterion("paramter5 in", values, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5NotIn(List<String> values) {
            addCriterion("paramter5 not in", values, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5Between(String value1, String value2) {
            addCriterion("paramter5 between", value1, value2, "paramter5");
            return (Criteria) this;
        }

        public Criteria andParamter5NotBetween(String value1, String value2) {
            addCriterion("paramter5 not between", value1, value2, "paramter5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video
     *
     * @mbg.generated do_not_delete_during_merge Sat Oct 13 11:12:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table video
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}