package com.kaige123.daomu.DAO.Bean;

public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.vid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long vcid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.vtitle
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String vtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.countDateM
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Integer countdatem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.freeTime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Integer freetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.paramter1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String paramter1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.paramter2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String paramter2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.paramter3
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String paramter3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.paramter4
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String paramter4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video.paramter5
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String paramter5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.vid
     *
     * @return the value of video.vid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.vid
     *
     * @param vid the value for video.vid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVid(Long vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.vcid
     *
     * @return the value of video.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getVcid() {
        return vcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.vcid
     *
     * @param vcid the value for video.vcid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVcid(Long vcid) {
        this.vcid = vcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.vtitle
     *
     * @return the value of video.vtitle
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getVtitle() {
        return vtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.vtitle
     *
     * @param vtitle the value for video.vtitle
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVtitle(String vtitle) {
        this.vtitle = vtitle == null ? null : vtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.countDateM
     *
     * @return the value of video.countDateM
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Integer getCountdatem() {
        return countdatem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.countDateM
     *
     * @param countdatem the value for video.countDateM
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setCountdatem(Integer countdatem) {
        this.countdatem = countdatem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.freeTime
     *
     * @return the value of video.freeTime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Integer getFreetime() {
        return freetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.freeTime
     *
     * @param freetime the value for video.freeTime
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setFreetime(Integer freetime) {
        this.freetime = freetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.paramter1
     *
     * @return the value of video.paramter1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getParamter1() {
        return paramter1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.paramter1
     *
     * @param paramter1 the value for video.paramter1
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setParamter1(String paramter1) {
        this.paramter1 = paramter1 == null ? null : paramter1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.paramter2
     *
     * @return the value of video.paramter2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getParamter2() {
        return paramter2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.paramter2
     *
     * @param paramter2 the value for video.paramter2
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setParamter2(String paramter2) {
        this.paramter2 = paramter2 == null ? null : paramter2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.paramter3
     *
     * @return the value of video.paramter3
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getParamter3() {
        return paramter3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.paramter3
     *
     * @param paramter3 the value for video.paramter3
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setParamter3(String paramter3) {
        this.paramter3 = paramter3 == null ? null : paramter3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.paramter4
     *
     * @return the value of video.paramter4
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getParamter4() {
        return paramter4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.paramter4
     *
     * @param paramter4 the value for video.paramter4
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setParamter4(String paramter4) {
        this.paramter4 = paramter4 == null ? null : paramter4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video.paramter5
     *
     * @return the value of video.paramter5
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getParamter5() {
        return paramter5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video.paramter5
     *
     * @param paramter5 the value for video.paramter5
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setParamter5(String paramter5) {
        this.paramter5 = paramter5 == null ? null : paramter5.trim();
    }
}