package com.kaige123.daomu.DAO.Bean;

public class Videotype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videotype.vtid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Long vtid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videotype.vtTypeName
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private String vttypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column videotype.vtSonTypeName
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    private Integer vtsontypename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videotype.vtid
     *
     * @return the value of videotype.vtid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Long getVtid() {
        return vtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videotype.vtid
     *
     * @param vtid the value for videotype.vtid
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVtid(Long vtid) {
        this.vtid = vtid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videotype.vtTypeName
     *
     * @return the value of videotype.vtTypeName
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public String getVttypename() {
        return vttypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videotype.vtTypeName
     *
     * @param vttypename the value for videotype.vtTypeName
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVttypename(String vttypename) {
        this.vttypename = vttypename == null ? null : vttypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column videotype.vtSonTypeName
     *
     * @return the value of videotype.vtSonTypeName
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public Integer getVtsontypename() {
        return vtsontypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column videotype.vtSonTypeName
     *
     * @param vtsontypename the value for videotype.vtSonTypeName
     *
     * @mbg.generated Sat Oct 13 11:12:28 CST 2018
     */
    public void setVtsontypename(Integer vtsontypename) {
        this.vtsontypename = vtsontypename;
    }
}